### ISSUE TITLE
Reporter does not detect build number on Semaphore

### ISSUE THREAD

**Issue by jaredmoody** [coverallsapp/coverage-reporter#55]
Here's my scenario that's not working:

1. Ran Jest and uploaded successfully with `--parallel`

```
./coveralls --parallel
 
⠀⠀⠀⠀⠀⠀[38;5;196m⣿[0m
⠀⠀⠀⠀⠀[38;5;196m⣼⣿⣧[0m⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
[38;5;196m⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶[0m  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀[38;5;196m⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁[0m⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀[38;5;196m⢠⣿⣿⣿⠿⣿⣿⣿⡄[0m⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀[38;5;196m⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀[0m⠀⠀
 
  v0.3.3

🔍 Detected coverage file: coverage/lcov.info
⭐️ Running in parallel mode. You must call the webhook after all jobs finish: `coveralls --done`
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
---
✅ API Response: {"message":"Job ##2198.1","url":"https://coveralls.io/jobs/118530597"}
- 💛, Coveralls
```

2. Attempted to call the webhook to finish:

```
./coveralls --done
 
⠀⠀⠀⠀⠀⠀[38;5;196m⣿[0m
⠀⠀⠀⠀⠀[38;5;196m⣼⣿⣧[0m⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
[38;5;196m⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶[0m  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀[38;5;196m⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁[0m⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀[38;5;196m⢠⣿⣿⣿⠿⣿⣿⣿⡄[0m⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀[38;5;196m⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀[0m⠀⠀
 
  v0.3.3

⭐️ Calling parallel done webhook: https://coveralls.io/webhook
---
✅ API Response: {"error":"No build matching CI build number  found"}
- 💛, Coveralls
```

I attempted to call the webhook directly with curl and received a similar message:

```
curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$SEMAPHORE_WORKFLOW_ID&payload[status]=done"
{"error":"No build matching CI build number d9334a96-6830-477f-92a2-867c7054a4c1 found"}
```

Next I changed my first parallel call to directly pass the job id, which did use the $SEMAPHORE_WORKFLOW_ID when reporting with `--parallel`, but then still did not on the `--done` step:

```
./coveralls --parallel --service-job-id=$SEMAPHORE_WORKFLOW_ID
 
⠀⠀⠀⠀⠀⠀[38;5;196m⣿[0m
⠀⠀⠀⠀⠀[38;5;196m⣼⣿⣧[0m⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
[38;5;196m⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶[0m  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀[38;5;196m⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁[0m⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀[38;5;196m⢠⣿⣿⣿⠿⣿⣿⣿⡄[0m⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀[38;5;196m⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀[0m⠀⠀
 
  v0.3.3

🔍 Detected coverage file: coverage/lcov.info
⭐️ Running in parallel mode. You must call the webhook after all jobs finish: `coveralls --done`
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
---
✅ API Response: {"message":"Job #57072beb-0895-44e4-a7fe-ccc892a72d55.1","url":"https://coveralls.io/jobs/118531465"}
- 💛, Coveralls
```

```
./coveralls --done --service-job-id=$SEMAPHORE_WORKFLOW_ID
 
⠀⠀⠀⠀⠀⠀[38;5;196m⣿[0m
⠀⠀⠀⠀⠀[38;5;196m⣼⣿⣧[0m⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
[38;5;196m⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶[0m  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀[38;5;196m⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁[0m⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀[38;5;196m⢠⣿⣿⣿⠿⣿⣿⣿⡄[0m⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀[38;5;196m⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀[0m⠀⠀
 
  v0.3.3

⭐️ Calling parallel done webhook: https://coveralls.io/webhook
---
✅ API Response: {"error":"No build matching CI build number  found"}
- 💛, Coveralls
```

Finally, what _does_ work is calling `coveralls --parallel --service-job-id=$SEMAPHORE_WORKFLOW_ID` followed by manually calling  the done webhook with curl.

**Comment by mrexox** [comment]
Hey! I've merged your PR and released it under v0.3.5. Could you please test if it works?

**Comment by jaredmoody** [comment]
This is looking good to me, build numbers detected, info all flowing into Coveralls! 🍻

**Comment by jaredmoody** [comment]
After some more usage today, I'm still seeing a problem executing `coveralls --done` - it doesn't seem to be working - I'm not seeing the coverage status reported back to Github. If I use curl, everything is fine.


Seems this issue needs to be re-opened.

Sample failure with binary:

```
curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls --done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 3147k  100 3147k    0     0  5298k      0 --:--:-- --:--:-- --:--:-- 5298k
 
⠀⠀⠀⠀⠀⠀[38;5;196m⣿[0m
⠀⠀⠀⠀⠀[38;5;196m⣼⣿⣧[0m⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
[38;5;196m⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶[0m  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀[38;5;196m⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁[0m⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀[38;5;196m⢠⣿⣿⣿⠿⣿⣿⣿⡄[0m⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀[38;5;196m⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀[0m⠀⠀
 
  v0.3.6

⭐️ Calling parallel done webhook: https://coveralls.io/webhook
---
✅ API Response: {"done":true,"url":"https://coveralls.io/builds/58834287","jobs":5}
- 💛, Coveralls
```

Sample success with curl:
```
curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$SEMAPHORE_WORKFLOW_ID&payload[status]=done"
{"done":true,"url":"https://coveralls.io/builds/58834287","jobs":5}
```

Since the API response is the same in both cases, I'm not sure how to debug this.

**Comment by mrexox** [comment]
Hey! Could you add a `--debug` option to `coveralls` call?

```bash
curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls --debug --done
```

It will print the payload it sends to coveralls.io

Looks like there are some parameters that affect coveralls backend. It can be our bug for Semaphore CI. Your debug output would help to investigate the issue.

**Comment by jaredmoody** [comment]
Sure, here's the output:

```
$ ./coveralls --debug --done

⠀⠀⠀⠀⠀⠀⣿
⠀⠀⠀⠀⠀⣼⣿⣧⠀⠀⠀⠀⠀⠀⠀ ⣠⣶⣾⣿⡇⢀⣴⣾⣿⣷⣆ ⣿⣿⠀⣰⣿⡟⢸⣿⣿⣿⡇ ⣿⣿⣿⣷⣦⠀⠀⢠⣿⣿⣿⠀⠀⣿⣿⠁⠀⣼⣿⡇⠀⢀⣴⣾⣿⡷
⠶⣶⣶⣶⣾⣿⣿⣿⣷⣶⣶⣶⠶  ⣸⣿⡟ ⠀⢠⣿⣿⠃⠈⣿⣿⠀⣿⣿⢠⣿⡿⠀⣿⣿⣧⣤⠀⢸⣿⡇⣠⣿⡿⠀⢠⣿⡟⣿⣿⠀⢸⣿⡿⠀⠀⣿⣿⠃⠀⢸⣿⣧⣄
⠀⠀⠙⢻⣿⣿⣿⣿⣿⡟⠋⠁⠀⠀ ⣿⣿⡇⠀ ⢸⣿⣿⠀⣸⣿⡟⠀⣿⣿⣾⡿⠁ ⣿⣿⠛⠛⠀⣿⣿⢿⣿⣏⠀⢀⣿⣿⣁⣿⣿⠀⣾⣿⡇⠀⢸⣿⡿⠀⠀⡀⠙⣿⣿⡆
⠀⠀⢠⣿⣿⣿⠿⣿⣿⣿⡄⠀⠀⠀ ⠙⢿⣿⣿⠇⠈⠿⣿⣿⡿⠋⠀⠀⢿⣿⡿⠁⠀⢸⣿⣿⣿⡇⢸⣿⣿⠀⣿⣿⣄⣾⣿⠛⠛⣿⣿⢠⣿⣿⣿ ⣼⣿⣿⣿ ⣿⣿⡿⠋⠀
⠀⢀⣾⠟⠋⠀⠀⠀⠙⠻⣷⡀⠀⠀

  v0.3.6

⭐️ Calling parallel done webhook: https://coveralls.io/webhook
---
⛑ Debug Output:
{
  "service_branch": "dev/coveralls-client",
  "service_build_url": "https://jetbuilt.semaphoreci.com/workflows/c0f285e8-79cd-4105-ab25-62b07b86a666",
  "service_job_id": "8fbc3c57-b316-4439-9911-5f5b4e1db34b",
  "service_job_url": "https://jetbuilt.semaphoreci.com/jobs/8fbc3c57-b316-4439-9911-5f5b4e1db34b",
  "service_name": "semaphore",
  "service_number": "c0f285e8-79cd-4105-ab25-62b07b86a666",
  "service_pull_request": "11320",
  "commit_sha": "89ecb1457410757ef278673f0064339864b80257",
  "repo_token": "YIS4FUu5lyBNdhDqv4tSeSLSB7Aigk3ry",
  "payload": {
    "build_num": "c0f285e8-79cd-4105-ab25-62b07b86a666",
    "status": "done"
  }
}
---
✅ API Response: {"done":true,"url":"https://coveralls.io/builds/58834287","jobs":5}
- 💛, Coveralls
```

The build_num looks the same as in my curl example that worked:

```

**Comment by mrexox** [comment]
Hey! I've tried to reporoduce this bug but for my repo everything seems to work fine.

![2023-04-14_12-08](https://user-images.githubusercontent.com/20262425/232000093-58f6a293-9909-481a-a1a2-fd043e0043b1.png)

- Job coverage (I have 1 job just to implement a parallel flow)
- Semaphore build stataus
- Build coverage

Which of these you don't have for your builds?

You can check the PR here: https://github.com/mrexox/sentry-sanitizer/pull/8

**Comment by mrexox** [comment]
Hey @jaredmoody, do you still have this issue? Can you please check my recent comment about it?

**Comment by jaredmoody** [comment]
I tried again and I am seeing Coveralls report back to Github - maybe I just didn't wait long enough the first time 🤷
